### ISSUE TITLE
Documentation Todo List

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts.github.io#71]
- [x] How all Roblox types are ambient `BasePart`, etc.
- [x] Macro math stuff for `Vector3`, `CFrame`, etc.
- [x] `.` vs `:` for function calls
- [x] Why RemoteEvent.OnServerEvent has `unknown` arguments
